export const ProjectEntries = [
  {
    backgroundImage: "",
    Title: "",
    Pupose: "",
    Resources: [""],
    Challenges: [""],
    Improvements: [""],
  },
  {
    backgroundImage: "",
    Title: "",
    Pupose: "",
    Resources: [""],
    Challenges: [""],
    Improvements: [""],
  },
  {
    backgroundImage: "",
    Title: "",
    Pupose: "",
    Resources: [""],
    Challenges: [""],
    Improvements: [""],
  },
  {
    backgroundImage: "",
    Title: "",
    Pupose: "",
    Resources: [""],
    Challenges: [""],
    Improvements: [""],
  },
  {
    backgroundImage: "",
    Title: "",
    Pupose: "",
    Resources: [""],
    Challenges: [""],
    Improvements: [""],
  },
];